config/routes.rb
BetterServed::Application.routes.draw do

  scope module: 'pub' do
    scope "(/:locale)" do
      get "q/:uuid", to: 'actions#show', as: :q
      get "a/:premise_id", to: 'actions#back_protection', as: :back_protection
      resources :requests, only: [:show]
      resources :items, only: [] do
        resources :requests, only: [:create]
        resources :feedbacks, only: [:create, :new]
      end
    end
  end
  scope "(:locale)" do
    resources :places, only: [] do
      resources :items, only: [:index] do
        member do
          get :download
        end
        collection do
          get :download_all
        end
      end
    end
    resources :premises do
      resources :places
    end
    resources :wizard, only: :index do
      collection do
        get :start
        post :setup
      end
    end

    get "home", to: "pages#home", as: "home"
    get "inside", to: "pages#inside", as: "inside"

    resources :dashboard, only: :index

    devise_for :users, skip: [:sessions]
    devise_scope :user do
      get "signup" => "registrations#new", as: :signup
      post "signup" => "registrations#new", as: :create_user
      get 'login' => 'sessions#new', as: :new_user_session
      post 'login' => 'sessions#create', as: :user_session
      delete 'logout' => 'sessions#destroy', as: :destroy_user_session
    end

    namespace :admin do
      root "base#index"
      resources :users
    end

  end
  scope '(:locale)' do
    root to: "pages#home"
  end
end

app/controllers/pub/actions_controller.rb
class Pub::ActionsController < ApplicationController
  layout 'pub'

  before_filter :find_item, only: :show

  def show
  end

  # protect from using back button to invoke action twice
  def back_protection
  end


  private

  def find_item
    @item = Item.where(uuid: params[:uuid]).first
    @place = @item.place
    @premise = @place.premise
  end

end

app/controllers/pub/feedbacks_controller.rb
class Pub::FeedbacksController < ApplicationController
  layout 'pub'

  before_filter :find_item, only: [:new, :create]

  def create
    @item.feedbacks.create(item_params)
  end

  def new
    @feedback = @item.feedbacks.build
  end

  protected

  def find_item
    @item = Item.where(id: params[:item_id]).first
    @place = @item.place
    @premise = @place.premise
  end

  def item_params
    params.require(:feedback).permit(:email, :content)
  end

end

app/controllers/pub/requests_controller.rb
class Pub::RequestsController < ApplicationController
  layout 'pub'

  def create
    @request = Request.new(type: params[:type], item_id: params[:item_id])

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_path(@request) }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

end

app/helpers/pub_helper.rb
module PubHelper

  def pub_title(title)

  end

end

app/views/pub/actions/back_protection.html.haml
.space-4
.well.well-lg
  = icon('info-circle', t('.scan_again'), class:'')

.space-10

app/views/pub/actions/show.html.haml
- title(t('request_for') + @premise.name)
%h3
.row#bp
  .col-xs-12
    .widget-box
      .widget-header
        %h5= t('.how_can_we_help')

      .widget-body
        .widget-main
          = button_to t('.waiter'), item_requests_path(@item, type: 'Order'), method: :post, class: "btn btn-info btn-block btn-lg", disable_with: t('.disable_order')
          = link_to t('.the_bill'),  item_requests_path(@item, type: 'Bill'), method: :post, class: "btn btn-primary btn-success btn-block btn-lg", disable_with: t('.disable_order')
          = link_to t('.feedback'), new_item_feedback_path(@item.id), class: "btn btn-primary btn-warning btn-block btn-lg"

:javascript
  var d = new Date();
  n = d.getTime();
  var place = "#{@place.name}";
  var item = "#{@item.name}";