config/routes.rb
BetterServed::Application.routes.draw do

  scope module: 'pub' do
    scope "(/:locale)" do
      get "q/:uuid", to: 'actions#show', as: :q
      get "a/:premise_id", to: 'actions#back_protection', as: :back_protection
      resources :requests, only: [:show]
      resources :items, only: [] do
        resources :requests, only: [:create]
        resources :feedbacks, only: [:create, :new]
      end
    end
  end
  scope "(:locale)" do
    resources :places, only: [] do
      resources :items, only: [:index] do
        member do
          get :download
        end
        collection do
          get :download_all
        end
      end
    end
    resources :premises do
      resources :places
    end
    resources :wizard, only: :index do
      collection do
        get :start
        post :setup
      end
    end

    get "home", to: "pages#home", as: "home"
    get "inside", to: "pages#inside", as: "inside"

    resources :dashboard, only: :index

    devise_for :users, skip: [:sessions]
    devise_scope :user do
      get "signup" => "registrations#new", as: :signup
      post "signup" => "registrations#new", as: :create_user
      get 'login' => 'sessions#new', as: :new_user_session
      post 'login' => 'sessions#create', as: :user_session
      delete 'logout' => 'sessions#destroy', as: :destroy_user_session
    end

    namespace :admin do
      root "base#index"
      resources :users
    end

  end
  scope '(:locale)' do
    root to: "pages#home"
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_many :requests
  has_many :feedbacks
  has_many :orders
  has_many :bills
  belongs_to :place
  validate :name, presence: true, length: {in: 1..256}
  validate :uuid, presence: true, uniqueness: true

  attr_accessor :item_count
  before_validation :set_uuid, on: :create
  before_create :create_qr_data_url


  def qr
    url = "http://#{ENV['DOMAIN']}/q/#{uuid}"
    qr = RQRCode::QRCode.new(url, size: 8, level: :h)
    qr.to_img
  end

  def qr_image_link(size = nil)
    png = qr
    png = qr.resize(size, size) if size
    png.to_data_url
  end

  def qr_file_name()
    name.gsub(/\s/, '_')
  end
  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end

  def create_qr_data_url
    self.qr_data_url = qr_image_link(200)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :setup_place, only: [:index, :download, :download_all]

  def index
    @items = @place.items
  end

  def download
    @item = @place.items.find(download_params[:id])
    send_data @item.qr.resize(400, 400), type: "image/png", filename: @item.qr_file_name
  end

  def download_all
    require 'zip/zip'
    items = @place.items
    path = "/tmp/#{@place.name}_qr_codes.zip"
    #stringio = Zip::ZipOutputStream.write_buffer do |zio|
    #  items.each do |item|
    #    zio.put_next_entry(item.qr_file_name + ".png")
    #    zio.write item.qr.resize(400, 400)
    #  end
    #end
    #stringio.rewind
    #binary_data = stringio.sysread
    #send_data binary_data, type: "application/zip", filename: "#{@place.name}_qr_codes.zip"

    Zip::ZipFile.open(path, Zip::ZipFile::CREATE) { |zipfile|
      items.each do |item|
        zipfile.get_output_stream(item.qr_file_name + ".png") { |f| f.puts item.qr.resize(400, 400) }
      end
    }
    send_file path, type: "application/zip"
  end


  protected

  def setup_place
    #TODO restrict to user
    @place = Place.find(params[:place_id])
  end

  def download_params
    params.permit(:id, :place_id)
  end

  def item_params
    params[:item].permit(:id)
  end

end

app/views/items/_item.html.haml
%tr
  %td= item.name
  %td= item.description
  %td
    = ace_thumbnail do
      .con
        %img.qr_90{src: item.qr_data_url}
        .text
          .inner
            %span= item.name
            %br
            = link_to download_place_item_path(@place, item), data: {rel: 'colorbox'}, class: 'cboxElement' do
              = icon('download')
            = link_to q_path(uuid: item.uuid), data: {rel: 'colorbox'}, class: 'cboxElement', target: '_blank' do
              = icon('link')

app/views/items/index.html.haml
- title t('items')

= link_to download_all_place_items_path(@place), target: '_blank' do
  .infobox.infobox-grey.infobox-small.infobox-dark
    .infobox-icon
      = icon("download")
    .infobox-data
      .infobox-content
        Download Qr codes

.space-6

- table do
  %thead
    %tr
      %th= t('phrases.name')
      %th= t('phrases.description')
      %th= t('qr')
  %tbody
    = render partial: "item", collection: @items




:javascript